### ISSUE TITLE
Appimage won't open

### ISSUE THREAD

**Issue by Hollowscope4022** [JMBeresford/retrom#107]
Im on arch and my specs are CPU :ryzen 7 5800x, GPU : AMD 7900XT, RAM: 32 GB, and im on plasma 6 wayland. Upon running I get this error before retrom force closes.
" ./Retrom_0.0.80_amd64.AppImage 
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
Segmentation fault (core dumped)"

**Comment by JMBeresford** [comment]
Can you try running the AppImage as such:

```sh
WEBKIT_DISABLE_COMPOSITING_MODE=1 ./retrom.AppImage
```

This may have unintended side-effects on the rendering of the app, but I am curious if it enables you to launch it.

**Comment by Hollowscope4022** [comment]
Thank you for the brief response, also kinda does a similar thing.
"WEBKIT_DISABLE_COMPOSITING_MODE=1 ./Retrom_0.0.80_amd64.AppImage
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
Segmentation fault (core dumped)"

**Comment by JMBeresford** [comment]
What version of Arch are you on, and what gfx drivers do you have installed if any?

**Comment by Hollowscope4022** [comment]
OS: Arch Linux x86_64,  Kernel: 6.10.10-arch1-1, and my gpu drivers are vulkan-radeon 1:24.2.3-1 from the extra repo.

**Comment by JMBeresford** [comment]
I see. This will be hard for me to debug, as I do not have a device that I can repro this on. I can only suggest verifying that your gfx config on your system has nothing crazy going on. Check for the existence of nvidia drivers, for example, as I know those can cause similar issues to what you are experiencing.

Hopefully someday I can get a more robust validation environment setup for AppImages, but for now there is not much else I can do here.

**Comment by Hollowscope4022** [comment]
No rush on debugging it, I also tried it on my steam deck and it works there, as for my arch desktop the only nvidia related package I have is nvidia-utils because obs-studio-rc/ffmpeg-obs relies on it. Not sure if this gives helpful info but these are the dependencies for it
"ffmpeg-obs optionally requires nvidia-utils: Nvidia NVDEC/NVENC support
:: libvdpau optionally requires nvidia-utils: driver for NVIDIA
:: vulkan-icd-loader optionally requires vulkan-driver: packaged vulkan driver"

**Comment by Hollowscope4022** [comment]
wait, that was it I uninstalled nvidia-utils and it just works.
