### ISSUE TITLE
Cannot launch docker compose example on portainer

### ISSUE THREAD

**Issue by sunbrolynk** [JMBeresford/retrom#114]
Error: Failed to deploy a stack: listing workers for Build: failed to list workers: Unavailable: connection error: desc = "error reading server preface: http2: frame too large"

Compose.yaml

services:
  retrom-db:
    image: postgres
    container_name: retrom-db
    hostname: retrom-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      TZ: "America/Denver"
      PGTZ: "America/Denver"
      POSTGRES_PASSWORD: xxxxxxxxxxxxxxxxxx
      POSTGRES_USER: xxxxxxxxxxxxxxxx
      POSTGRES_DB: retrom

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  retrom:
    build:
      context: ../
      dockerfile: docker/service.Dockerfile
    container_name: retrom
    hostname: retrom
    ports:
      - 5101:5101
    volumes:
      - /mnt/nas/gaming/Games:/lib1
      - /docker/retrom/config:/config
    depends_on:
      - retrom-db

  retrom-web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
    container_name: retrom-web
    hostname: retrom-web
    ports:
      - 3000:3000
    environment:
      VITE_RETROM_WEB_PORT: 3000
      VITE_RETROM_HOST: 5101
    depends_on:
      - retrom

**Comment by sunbrolynk** [comment]
i think i realized whats wrong.

**Comment by JMBeresford** [comment]
What is your networking config? Is the service behind a reverse proxy? If so, is there any SSL/TLS being applied and how exactly are you connecting the client to the service? I.e. what url are you putting into the client to connect to

**Comment by sunbrolynk** [comment]
it was failing to pull the images because i didnt have them specified where to go or downloaded locally yet. all running now!
