### ISSUE TITLE
Manually updating metadata seems not working

### ISSUE THREAD

**Issue by Kimbaras** [JMBeresford/retrom#142]
And it's me again... I'm stating to be your nightmare :P

This time the issue seems to be with the manual update of the metadata.

Let's say I've got the folder for Alien Isolation.

IDGB identify that with the mobile port which has a separate IDGB ID. I got to Edit > Manual > insert the correct IGDB ID > click on "Update Medatada" and nothing happens in the meaning of "the button is not doing anything"

![metadata](https://github.com/user-attachments/assets/d9028502-0fbc-4dac-b22a-1d082f7546a7)

If instead I got to the "Search IGDB" tab starting with the automatic data
![auto_metadata](https://github.com/user-attachments/assets/1f616ffd-8924-4d8e-982e-98eb0b25e270)

Then manually entering the correct ID and associating the game
![manual_meta](https://github.com/user-attachments/assets/6843a1db-f13f-403c-ad23-b6d742888b56)

And update the metadata, this way the data are correctly updated (you can see the different cover in the background of the screens and the correct one after updating)
![ok](https://github.com/user-attachments/assets/3e814146-7b18-4840-9a41-59647ad47624)

So I'd say the manually updating the metadata is not totally broken as it's seems to work, just not from the intended tab?
Or am I misunderstanding the intended behaviour?

Thanks!

**Comment by JMBeresford** [comment]
It is a bit misleading, but editing the IGDB ID manually there will not trigger an update of the remaining metadata. It is a simple one-off manual change of the ID (and anything else you modify in the tab).

I think I will opt to simply remove that field from the manual tab and change the button to 'Confirm' to make this more clear.

Note also that you currently have your 'PC' platform mapped to the [PC-9800](https://www.igdb.com/platforms/pc-9800-series) which will make searching IGDB less accurate (this is why you currently need to manually add the IGDB ID, or uncheck that box to find the correct game). You can fix this by going to the `Platforms > Match Platforms` menu item and change it to `PC (Microsoft Windows)` which is IGDBs 'PC' entry.

**Comment by Kimbaras** [comment]
Got it, I agree with your proposal of removing the field from the manual tab. As you correctly said, it's a bit misleading.

And thanks for the tip about the PC platform!
