### ISSUE TITLE
removing old files/folders

### ISSUE THREAD

**Issue by ggfools** [JMBeresford/retrom#144]
I moved some files around in my retrom folder and after a library scan it recognizes where the files are located now, but still shows the entires for where the files used to be, how do I get the library scan to remove non-existant files?

**Comment by JMBeresford** [comment]
This is an option I plan to add to the Update Library job. For now, the only way is to manually remove the entries via the UI (platforms, unfortunately, do not have UI implementations for this yet).

Your other workarounds are:
1. Use the Delete Library job (this just wipes the DB, not the files) and re-scan from scratch
2. Access the DB yourself (any method to access a psql database will work) to remove the platforms/games that are not longer valid.

I hope to have the proper solution shipped relatively soon.

**Comment by JMBeresford** [comment]
Closing in favor of #101
