### ISSUE TITLE
Enhancement request: Enable persistent user-defined window settings

### ISSUE THREAD

**Issue by mylesvarns** [JMBeresford/retrom#145]
Enhancement request.

Retrom appimage appears to have 1280x720 non-fullscreen set as the persistent window size to use based on the tauri.conf.json and my experience on the steamdeck. While this is fine on Desktop devices with full mouse, keyboard, and desktop display environment, devices such as the steamdeck, cannot change the resolution of the retrom client in their non-desktop environments to fit the actual screen-size. Can a fullscreen or borderless resolution setting be available within the app itself, as well as keeping that setting persistent across restarts be available for these instances?

**Comment by JMBeresford** [comment]
Yes, this will be added to a UI option eventually. Handhelds such as the steam deck will likely want to simply default to the full-screen mode once it is implemented (#103), but a switch in UI will be available to go back and forth regardless.

You should be able to toggle fullscreen with Retrom as it is, so long as your DE supports it. I have not tested this outside of macOS and windows, but the default keybinds to toggle 'Fullscreen' for an application in those OSs works as expected ( e.g. alt-enter for windows ). See screen recording for example. I understand there are many DE that could be used in a Linux environment, and they may not all operate the same way here -- but this may be something you can look into as well.

I agree that persisting the window config should be implemented, however, and will look into that in the interim.
