### ISSUE TITLE
Feature request : Download igdb images locally to allow retrom to work in an air gapped environnement

### ISSUE THREAD

**Issue by aureliensoria** [JMBeresford/retrom#151]
Currently, retrom does not store games medias. It is reliant on igdb each time a game page is loaded.
It would be nice feature to be able to download them server side to lessen igdb dependency.
Thank you !

**Comment by JMBeresford** [comment]
I plan to implement a server-side cache of metadata images at a minimum (perhaps an additional client-side cache) with the metadata overhaul that comes with #102 . Going to close this in favor of that issue, please follow it for updates if you wish.
