### ISSUE TITLE
Automatic matching chooses results from other platforms

### ISSUE THREAD

**Issue by scottrice** [JMBeresford/retrom#168]
### Describe the bug
When importing a new library, a bunch of my games got incorrectly matched. The matches generally had the correct string inside the matched name, but was generally some variant (like a deluxe version, or a remake). Notably these are all on different platforms. When I went to fix these issues I found that simply doing the same search with the "Restrict options by platform" checkbox almost always gave me the correct result first.

### Steps To Reproduce
1. Get a brand new retrom installation
2. Set up a folder with files named after any of the games below
3. Import the library and observe the matches
4. Notice that the matches are close, but not correct.

Games where this happened to me:

| Filename | Matched game |
| ---- | ---- |
| Chrono Trigger | Chrono Trigger Character Library |
| GoldenEye 007 | 007 GoldenEye |
| Legend of Zelda - A Link to the Past | Legend of Zelda - A Link to the Past and Four Swords | 
| Star Fox 64 | Star Fox 64 3D |
| Super Smash Bros. Melee | Super Smash Bros. Melee: 20XX Edition |

### Expected behavior
Matching only searches for games on the specific platform to give better results.

**Comment by JMBeresford** [comment]
Filtering on the platform is opt-in because it is not uncommon for platform matches to be incorrect until manually matching them. When this happens, it is also common to encounter an empty result when searching for games with that option enabled which is very confusing to new users.

It does, however, still prioritize the platform in the listed results -- and this is something that can also be done in the full-library metadata update job. Am I understanding your issue correctly?

**Comment by x-rOtT** [comment]
_The matches generally had the correct string inside the matched name, but was generally some variant (like a deluxe version, or a remake)._

**Comment by JMBeresford** [comment]
Yes I understand, the matching done in the manual IGDB search dialog and the matching done in the bulk library operation differ in certain respects. **The latter will be updated to match the former. I will also update it to prioritize exact matches, however it should be noted that this will likely still not lead to perfect results.**

IGDB API results are generally not in an order you would expect, and we fallback to the first result in the response. There will almost certainly always be a need for non-trivial manual clean-up/matching.
