### ISSUE TITLE
Could not load configuration

### ISSUE THREAD

**Issue by hbintook** [JMBeresford/retrom#170]
I am trying to run retrom, but it gives me an error. I already put config.js at config directly. I am using unraid.

Could not load configuration: missing field `connection`

Update: I have changed the name of the file config to config.json, but it gives me a new error.

Could not load configuration: expected `,` or `}` at line 18 column 19 in ../config/config.json

My config.json 
```json
{
  "connection": {
    "port": 5101,
    "db_url": "postgres://retrom-db:retrom-db@retrom-db/retrom"
  },
  "content_directories": [
    {
      "path": "/library1",
      "storage_type": "MultiFileGame"
    },
    {
      "path": "/library2",
      "storage_type": "SingleFileGame"
    }
  ],
  "igdb": {
    "client_secret": "mysecret",
    "client_id": "myid"
  }
}
```

**Comment by hbintook** [comment]
I am using unraid

**Comment by JMBeresford** [comment]
That error indicates the JSON is malformed. Try running it through a JSON linter ( easily found through google ), but what you posted here looks correct to me at a glance.

Closing this, as issues are for bug reports not technical support. If you still need assistance with this after checking your formatting I would be happy to help in our [discord server](https://discord.gg/tM7VgWXCdZ)!
