### ISSUE TITLE
AppImage Fails on Fedora

### ISSUE THREAD

**Issue by NovaCyntax** [JMBeresford/retrom#185]
### Describe the bug
When launching Retrom AppImage on Bazzite OS (Immutable Fedora distro designed for gaming), the window remains white. The following error is displayed in the terminal:
`Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...`

### Steps To Reproduce
1. Launch Retrom AppImage
2. Observe

### Expected behavior
Application interface launches

### Screenshots
![image](https://github.com/user-attachments/assets/a3066361-f262-4b8e-bf3a-924b3571f94d)

### Environment (please complete the following information _where applicable_):
 - Bazzite OS 41

### Logs
`Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...`

### Additional context
The application works fine on my other devices. This OS is commonly used on the Steam Deck and similar Linux-based gaming PCs.

**Comment by JMBeresford** [comment]
@NovaCyntax can you confirm that the fixe(s) mentioned in #107 do not work for your case?

**Comment by NovaCyntax** [comment]
` WEBKIT_DISABLE_COMPOSITING_MODE=1 ./Retrom_0.0.80_amd64.AppImage' did not resolve the issue. Additionally, my system has an AMD GPU, so the Nvidia suggestion wouldn't help. Bazzite uses a "Wayland to X11 Video Bridge", and does some funky things with graphics, so I would imagine that's what's causing it.

**Comment by JMBeresford** [comment]
You can still have nvidia utilities installed w/ amd GPU being present, this is not uncommon. I would suggest taking a look at your installed packages just in case, I also may have a potential fix for this incoming in next release based on some new info I encountered.

**Comment by JMBeresford** [comment]
@NovaCyntax Could you try the AppImage from [this pre-release build](https://github.com/JMBeresford/retrom/releases/tag/retrom-v0.4.5-pre.401bcc5d22c144e0b8d99c892997bd1a0f1dfff3)? It is currently building, should be available within 10m of this comment

**Comment by NovaCyntax** [comment]
I tested the (old) AppImage on a Fedora 41 KDE Edition install as well (to see if it was an issue with Bazzite in particular), and received the same result. I will try the new AppImage once I see it. The .rpm package works fine on Fedora 41 (but Bazzite is very restricted, so it doesn't play nicely with .rpm files). For what it's worth, I intend to stay on Fedora 41, I was just testing Bazzite while distrohopping.

**Comment by JMBeresford** [comment]
@NovaCyntax Interesting, I know many people have had success w/ the AppImage across many common distros ( barring the odd issue w/ gfx drivers / nvidia utilities ) prior to this fix.

I would suggest using the AppImage if the performance is acceptable, as none of the other Linux distribution methods support the auto-update mechanism. Could you perhaps elaborate on the performance issues when using the AppImage?

**Comment by NovaCyntax** [comment]
With the AppImage, the "framerate" when using the application is noticeably lower (e.g. when menus are expanded). This may only be visible because I have a higher refresh rate on my monitor.

**Comment by JMBeresford** [comment]
@NovaCyntax Perhaps the official non-debug release will fare better ( v0.4.5, which is now available ), but I will close this now pending any other reports of performance issues with the AppImage. Let me know if you encounter any other issues!
