### ISSUE TITLE
Feature Request / Idea: Steam Deck Enhancements

### ISSUE THREAD

**Issue by Ronald-Diemicke** [JMBeresford/retrom#210]
So - This seems like an awesome project. I'm thinking of using this with my steamdeck. My biggest concern would be how easy it is to navigate from the interface, but also it'd be neat to figure out how this could 'hook in' with steam on the device to make it easier to go from picking a game, to running the executable (and figuring out what to do for native linux runtimes vs installers for windows that'd need to run in proton), to getting it into steam itself.

**Comment by Ronald-Diemicke** [comment]
Missed that fullscreen + controller support was already in! Need to play with it some!

**Comment by JMBeresford** [comment]
@Ronald-Diemicke Yes, fullscreen and controller support is present -- though not fully featured yet ( as compared to 'desktop' mode ).

There is also already steam library integration as described in the [README](https://github.com/JMBeresford/retrom#steam).

What, if anything, is _not_ currently supported that you would like to see in Retrom in the future?

**Comment by Ronald-Diemicke** [comment]
Got it!

I had the time to finally start messing with this... to do a smaller sample set, I pointed it at my GOG folder...

I did run into a bug with full screen mode that I already logged in #215 ...

The biggest issue I see, at least for how I'm trying to use this, is that it doesn't seem to treat non-emulator games as first class citizens (maybe I'm just doing it wrong?)... It seemed to "download" the game (not sure where it went?), but there wasn't a way to 'install it'.

For my uses, I'm trying to use this with my steamdeck, so it'd be neat if I could tell this somehow to setup a wine folder for this game, download the exe installer, then run it... then once it was done installing, have the game be associated to that installed location, install any redist files needed (or all in ones to cover bases?) and then also add it into steam as a game... so I didn't _need_ to go into Retrom to run it (which is also important because if you need different controller profiles for different games, this could be annoying running them through Retrom...)

**Comment by JMBeresford** [comment]
Understood. Yes, as per the description Retrom has a "focus on emulation". Interoperability w/ native games is not currently supported outside of the Steam integration. Working w/ GOG installers is something that has been previously discussed, and is certainly something that I hope to work on sometime soon.

For now, just be aware that Retrom is emulation-first and support for native games is still in the early phases of design. Will close this for now, feel free to open further discussion in the discussion section if you would like!

**Comment by Ronald-Diemicke** [comment]
Bummer but understandable. I'll check back in on this later then! Using Romm right now for emulation since it has the EmulatorJS pieces built in already. Best of luck!
