### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by NovaCyntax** [JMBeresford/retrom#90]
Was excited to try this, since I've tried to install the "romm" program and had nothing but problems the few times I've tried the last couple years. Great documentation, simple and to the point, and works great!

Only thing I've noticed that I would like is the ability to hide (or possible rename/delete) files/folders detected by the program. I use Syncthing to synchronize data between a couple devices, and a mandatory ".syncthing" folder (with nothing in it) is placed in each directory. These directories appear in Retrom currently. 

This is an amazing first release and I can tell that a lot of work was put into it.

**Comment by JMBeresford** [comment]
Thanks much!

Can you elaborate on the exact context of the entries you would like to delete? Your desired behavior should be already possible for folders/files that show up as "games" or "game files". If it is showing up as a platform, then there is no other way than to manually hit the DB to update the relevant rows (obviously less than ideal). See the screenshots for how to delete games/game files.

![image](https://github.com/user-attachments/assets/531c779c-4642-49ec-926f-09e5e6d1c30b)
![image](https://github.com/user-attachments/assets/4d2877d3-73ec-468c-8832-73ef026fb5e2)


The ability to hide/delete/rename platforms is already implemented in the service, just need to update the UI to facilitate the actions. I'll have a ticket for this shortly, and will likely address it soon.

**Comment by NovaCyntax** [comment]
![image](https://github.com/user-attachments/assets/b194bb92-5ec7-40fd-94c9-730181d3ab35)


Does "Delete" remove the file from my filesystem, or just from the database? Also, will a re-scan cause it to re-appear? There are other folders as you can see, containing BIOS and such from some of the emulators that I use. I didn't want to risk hitting delete and losing things

**Comment by JMBeresford** [comment]
The confirmation dialog will allow you to do one of:

1. Delete from disk (also removes from the database entirely)
2. Only mark it as deleted in the database (sets a 'deleted' flag), subsequent scans will ignore that directory

There are plans to add a third option:
3. Delete from database w/o blacklisting (removes the DB entry, but subsequent scans will pick it back up)

**Comment by NovaCyntax** [comment]
Great, good to know!
