### ISSUE TITLE
Bash Script to Reorganize ROM Directory

### ISSUE THREAD

**Issue by NovaCyntax** [JMBeresford/retrom#91]
When installing this program, I had to re-organize my filesystem a bit. I understand that this will probably be an issue for others, so I wrote a quick bash script that worked for my library. Essentially, recursively scans through a directory of roms, detects the filenames, and puts them into a folder for you. It does the same thing for every file, which can be beneficial if you have .srm, .state, or other files - it can also be harmful if there are files that you do not want moved to other folders, so use at your own risk!

```#!/bin/bash

### Checking if user provided a directory ###
if [ -z "$1" ]; then
    echo "Usage: $0 /path/to/your/rom/directory"
    exit 1
fi

### Directory containing roms and save files ###
root_dir="$1"

### Main function ###
organize_roms() {
    for file in "$1"/*; do
        if [ -d "$file" ]; then
            # Recursively process sub-directories
            organize_roms "$file"
        elif [ -f "$file" ]; then
            # Get the filename and extension
            filename=$(basename "$file")
            extension="${filename##*.}"
            name="${filename%.*}"

            # Define the target directory based on the file name
            target_dir="$1/$name"

            # Check if the file is already in a correctly named directory
            if [ "$(basename "$1")" != "$name" ]; then
                # If the directory doesn't exist, create it
                if [ ! -d "$target_dir" ]; then
                    mkdir "$target_dir"
                fi

                # Move the ROM or save file into the correct directory
                mv "$file" "$target_dir/"
            fi
        fi
    done
}

### Function call ###
organize_roms "$root_dir"
```

**Make a backup of your data, or execute a dry-run before running the script! It worked for me, but might not for you.**

To run:
1. Save the above code as "organize_roms.sh" (or whatever you prefer)
2. Run "chmod +x organize_roms.sh"
3. Run "./organize_roms.sh /path/to/your/roms/folder"

**Comment by JMBeresford** [comment]
Thanks for the contribution!

Eventually the restriction on file/directory structure will be gone, and other more flexible configs will be supported.
