### ISSUE TITLE
Cannot change game

### ISSUE THREAD

**Issue by Bovive** [JMBeresford/retrom#92]
I had a couple games match incorrectly with IGDB. When I try to enter the name or IGDB ID it doesn't match anything. I tried this with the web and desktop clients. Interestingly enough, most of the matches that matched wrong or did not match resulted the same using SharewareZ, which also uses the IGDB metadata. I look forward to seeing where you go with this!

**Comment by JMBeresford** [comment]
Yes, I think matching by IGDB ID was recently inadvertently broken. Will look to fix this soon.

Regarding the similarity in matching, yes IGDB's API is fairly linear in how you can use it to search games. This means most software that uses it will fail in similar ways, unless heavy-handed custom sorting/filtering is done on top of the search results.

**Comment by JMBeresford** [comment]
@Bovive New update should handle searching on IGDB ID as expected now. Let me know if updating does not resolve your issue, ideally with info such as which games you cannot find and which IGDB ids you are searching

**Comment by Bovive** [comment]
> @Bovive New update should handle searching on IGDB ID as expected now. Let me know if updating does not resolve your issue, ideally with info such as which games you cannot find and which IGDB ids you are searching

Looks like the ID is working correctly now. The names might need some work. Let's try to match it to Above Snakes because it is a good example of a game that matches incorrectly.

IGDB URL: https://www.igdb.com/games/above-snakes
Auto matches as Snake, Snake, Snake! (Does the same thing on SharewareZ)
Search by the correct name only (Above Snakes) = no results.
Search by ID from IGDB = Correct result.

This is what you would see searching by name on SharwareZ, which matches by the first result (Snakes, Snakes, Snakes!) as seen here. 

![sharewarez](https://github.com/user-attachments/assets/e7800532-c4cc-475b-936e-6b541d9af85e)

Since you are auto matching to that first result, you must be pulling the correct names when trying to match it. It does not pull any names when trying to search on the user end, at least for Above Snakes.

Trying any name gave unexpected results:
 
Mario: Mario Bros Special
Luigi: No Result
Pacman: No Result

I think on the user side it must be filtering out more than it should. These are the results I would expect:

![Mario](https://github.com/user-attachments/assets/c30ba49f-d3da-4a1f-b547-be060b031905)

![Luigi](https://github.com/user-attachments/assets/32b8ae47-0142-4585-b03c-80110731b3e6)

![Pacman](https://github.com/user-attachments/assets/f384096e-64e7-4f93-bd80-7ca448de4972)

Hope that helps!

**Comment by JMBeresford** [comment]
Ah, yes you should ensure that your platforms were matched correctly after a metadata update. Searching for a game will filter the results to that game's platform (if that platform has been matched) only.

This is definitely something that should be made more clear to the user, and ill work on that soon.

You can check your platform matches via platforms > match platforms in the menu

**Comment by JMBeresford** [comment]
Notably, IGDB id searching circumvents that platform level filtering.

**Comment by Bovive** [comment]
That makes sense. Above Snakes was PC though, so that one didnt result anything.

**Comment by JMBeresford** [comment]
@Bovive Perhaps I am unclear on what you mean, but when I search for `above snakes` on a game entry that belongs to a matched `PC (Microsoft Windows)` platform I get the correct game in the results.

Note that `PC (Microsoft Windows)` is what IGDB uses to classify PC games. Was there another behavior you were expecting that I might be overlooking?

https://github.com/user-attachments/assets/9560a6cb-da05-4cd3-b331-bea8faf1798b

**Comment by Bovive** [comment]
Good idea with the video. Let me share mine so you can see what is happening.


https://github.com/user-attachments/assets/bdde6771-8dd0-4f91-b77a-e334fae79397

So it matched the games as I expected it to when first scanned, but it set my library as "PC-9800 Series". Once I changed the platform for my library to "PC (Microsoft Windows)" I was able to update the match as expected. 

From a user perspective I would not expect it to match games under an incorrect library. I think either options would make it more clear from my end:

1) Prompt a confirmation that the library is correctly matched to the platform.
2) Only auto-match from the platform that was confirmed as correct by the user.

Or something along those lines.

**Comment by JMBeresford** [comment]
@Bovive 100% agreed, the intention is to include those points as a flow similar to that of the initial setup. I'll increase the priority of that, as I can see this being an issue for many. Thanks! Closing for now. Feel free to re-open if you have other concerns. I'll make a new ticket to handle this UX issue.
